# Generated by Django 5.1.1 on 2024-09-13 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 9, 14)),
            preserve_default=False,
        ),
    ]
