# Generated by Django 5.1.1 on 2024-10-09 17:20

import django.db.models.deletion
import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='', validators=[petstagram.photos.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tagged_pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_pets', to='pets.pet'),
        ),
    ]
