# Generated by Django 5.0.4 on 2024-10-12 11:59

import django.db.models.deletion
import django_web_framework_ex.django_ex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=200, validators=[django_web_framework_ex.django_ex.validators.validate_league_name])),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, validators=[django_web_framework_ex.django_ex.validators.validate_team_name])),
                ('players', models.IntegerField(validators=[django_web_framework_ex.django_ex.validators.validate_team_players])),
                ('team_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='django_ex.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django_web_framework_ex.django_ex.validators.validate_player_age])),
                ('price', models.BigIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='django_ex.team')),
            ],
        ),
    ]
