# Generated by Django 5.0.4 on 2024-10-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_league',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='django_ex.league'),
        ),
    ]
