# Generated by Django 5.1.2 on 2024-10-13 20:38

import django_web_framework_ex.django_ex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ex', '0002_alter_team_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, unique=True, validators=[django_web_framework_ex.django_ex.validators.validate_team_name]),
        ),
    ]
