# Generated by Django 5.1.1 on 2024-10-06 20:49

import django.db.models.deletion
import forumApp.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'required': "The title should be entered or i'll ban you!!!"}, max_length=100, validators=[forumApp.posts.validators.check_if_bad_words_are_used_in_title]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, validators=[forumApp.posts.validators.check_author_name])),
                ('content', models.TextField(validators=[forumApp.posts.validators.content_length_validator])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
