# Generated by Django 5.1 on 2024-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music_file_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
