# Generated by Django 5.1 on 2024-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_music_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
